Repository kids-first/kf-ui-release-coordinator, pull requests merged in 2019-11, with the labels that each got.

#171 ⬆️ Upgrade dependencies
  package.json
  yarn.lock
Labels: refactor

#170 🐛 List studies by name when confirming release
  src/forms/NewReleaseForm.js
Labels: bug

#172 🐛 Fix queries
  src/queries.js
  src/views/Service.js
Labels: bug

#173 ✨ Add api status to header
  package.json
  src/containers/HeaderContainer.js
  src/queries.js
Labels: feature

#175 🐛 Reload new profile sign-ins
  src/components/Header.js
  src/containers/HeaderContainer.js
Labels: bug

#179 ✨ Use GraphQL mutation to update release description markdown
  src/App.css
  src/components/MarkdownEditor.js
  src/index.js
  src/mutations.js
  src/views/Release.js
Labels: refactor

#180 ✨ Add release notes component to release page
  package.json
  src/components/MarkdownEditor.js
  src/components/ReleaseNotes.js
  src/mutations.js
  src/queries.js
  src/views/Release.js
  yarn.lock
Labels: feature

#181 ✨ Add release notes page listing out all published releases' notes
  src/App.css
  src/components/Header.js
  src/components/MarkdownEditor.js
  src/components/NoteItem.js
  src/components/NotesList.js
  src/components/StudyNote.js
  src/components/utils.js
  src/containers/Root.js
  src/queries.js
  src/views/ReleaseNotes.js
Labels: feature

#183 👷‍♂️ Add agent label
  Jenkinsfile
Labels: devops

#185 🐛 Fix mm/dd/yyyy format date utility function
  src/components/utils.js
Labels: bug
