Repository kids-first/kf-ui-release-coordinator, pull requests merged in 2019-03, with the labels that each got.

#120 ✨ Add auth0
  .env
  package.json
  src/Auth.js
  src/actions/auth.js
  src/containers/Root.js
  src/globalConfig.js
  src/reducers/auth.js
  src/views/Callback.js
  src/views/Login.js
  yarn.lock
Labels: feature

#121 🚨 Add prettier configuration
  package.json
  prettier.config.js
  src/App.js
  src/Auth.js
  src/actions/auth.js
  src/actions/index.js
  src/actions/studies.js
  src/components/Events.js
  src/components/MarkdownEditor.js
  src/components/PublishHistory.js
  src/components/ReleaseList.js
  src/components/ReleaseReportSummary.js
  src/components/ReleaseTimeline.js
  src/components/ServiceList.js
  src/components/StatusBadge.js
  src/components/StudiesTable.js
  src/components/TaskList.js
  src/components/Tasks.js
  src/containers/HeaderContainer.js
  src/containers/Releases.js
  src/containers/Root.js
  src/containers/StudiesContainer.js
  src/forms/NewReleaseForm.js
  src/forms/NewService.js
  src/index.js
  src/reducers/auth.js
  src/reducers/index.js
  src/reducers/releases.js
  src/reducers/studies.js
  src/utils/index.js
  src/views/Callback.js
  src/views/NewService.js
  src/views/Profile.js
  src/views/Release.js
  src/views/Service.js
  src/views/Services.js
  src/views/Status.js
  src/views/Study.js
  yarn.lock
Labels: refactor

#122 ♻️ Refactor Auth0 callback function to provide user profile data
  src/Auth.js
  src/actions/auth.js
  src/views/Callback.js
Labels: refactor

#123 🔧 Add netlify.toml configuration
  netlify.toml
Labels: bug

#124 ♻️ Refactor docker setting by adding arg Auth0 Redirect URI
  Dockerfile
Labels: refactor

#128 🔧 Add build vars for master
  netlify.toml
Labels: devops

#129 ⬆️ Upgrade yarn deps
  yarn.lock
Labels: refactor

#130 🐛 Add protocol to redirect url
  netlify.toml
Labels: bug

#131 🚨 Update to new prettier standard
  prettier.config.js
  src/Auth.js
  src/actions/auth.js
  src/actions/index.js
  src/actions/studies.js
  src/components/Events.js
  src/components/MarkdownEditor.js
  src/components/PublishHistory.js
  src/components/ReleaseList.js
  src/components/ReleaseReportSummary.js
  src/components/ReleaseTimeline.js
  src/components/ServiceList.js
  src/components/StudiesTable.js
  src/components/TaskList.js
  src/components/Tasks.js
  src/containers/HeaderContainer.js
  src/containers/Releases.js
  src/containers/Root.js
  src/containers/StudiesContainer.js
  src/forms/NewReleaseForm.js
  src/forms/NewService.js
  src/index.js
  src/reducers/auth.js
  src/reducers/index.js
  src/reducers/releases.js
  src/reducers/studies.js
  src/registerServiceWorker.js
  src/views/Callback.js
  src/views/Login.js
  src/views/NewService.js
  src/views/Profile.js
  src/views/Release.js
  src/views/Service.js
  src/views/Services.js
  src/views/Status.js
  src/views/Study.js
Labels: refactor

#132 🐛 Fixes react-table selection
  package.json
  src/actions/studies.js
  yarn.lock
Labels: bug

#133 🐛 Fix new service form
  src/forms/NewService.js
Labels: bug

#134 🔥 Remove ant
  config-overrides.js
  package.json
  public/index.html
  src/components/Events.js
  src/components/MarkdownEditor.js
  src/components/Nav.js
  src/components/Progress.js
  src/components/ReleaseReportSummary.js
  src/components/ServiceList.js
  src/components/StatusBadge.js
  src/components/Steps.js
  src/components/Tag.js
  src/components/TaskList.js
  src/components/Tasks.js
  src/containers/HeaderContainer.js
  src/containers/Root.js
  src/forms/NewReleaseForm.js
  src/forms/NewService.js
  src/views/Login.js
  src/views/NewService.js
  src/views/Profile.js
  src/views/Release.js
  src/views/Releases.js
  src/views/Service.js
  src/views/Services.js
  src/views/Study.js
  yarn.lock
Labels: refactor
